name: flutter_register_component
description: A Flutter package for user registration form with email, password, first name, and last name fields.
version: 1.0.0
homepage: https://github.com/davideloddeDev/flutter-register

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
